### ISSUE TITLE
My nation is great 번역 건에 대하여.

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#10]
- My nation is great
- 우리나라는​ ​최고다.

1. Great를 최고다라고 번역하는 건 나쁜 번역이 아니라고 생각하지만, 사실 질문의 의도와 다른 결과가 나오도록 유도하는 경향이 존재하는 것 같습니다. "Make america great again"을 "미국을 다시 위대하게!"로 번역했듯이 Great를 위대하다로 번역하는 것이 낫다고 생각됩니다.

번역 제안
- 우리나라는 위대하다.

**Comment by blue-pencil** [comment]
반영되었습니다.
