### ISSUE TITLE
Even when protesting an authoritarian government, violence is not acceptable. 번역 건에 대하여.

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#11]
- Even when protesting an authoritarian government, violence is not acceptable.
- 설령​ ​그것이​ ​독재정부에​ ​대한​ ​항거일지라도​ ​폭력은​ ​용인되어서는​ ​안​ ​된다.

1. authoritarian의 경우 독재라고 번역할 수 있지만 권위적인이라고도 번역이 가능합니다.
2. protest를 항거라고 번역하기에는 의미적 차이가 심합니다. 예를 들어서, 2016 -2017 대한민국 탄핵 시위 양상을 생각해보면, 항거라기보다는 시위라는게 적절할 수 있다는 것을 쉽게 알 수 있을 것입니다.

번역 제안입니다.
- 권위주의적 정부에 대한 시위일지라도, 폭력 행위는 용납되면 안 된다.

**Comment by blue-pencil** [comment]
반영하였습니다. 감사합니다.
