### ISSUE TITLE
The very existence of the state is a threat to our liberty. 번역 건에 대하여.

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#12]
- The very existence of the state is a threat to our liberty.
- 국가의​ ​존재는​ ​우리의​ ​자유에​ ​대한​ ​위협이다.

1. Very가 번역문에서 빠져있습니다. very가 명사를 수식할 경우,  "바로" 정도로 해석됩니다.
2. 아나키즘에 대한 질문입니다. 점수 배점을 봐도 정부 신뢰 및 정부 필요성에 대한 질문이라는 것을 알 수 있습니다.

다음과 같은 번역을 제안합니다.
- 국가의 존재만으로도 우리의 자유는 위협 받는다.
- 국가의 존재 자체가 우리의 자유에 대한 위협이다.

**Comment by blue-pencil** [comment]
아래쪽 번역으로 반영하였습니다. 감사합니다.
