### ISSUE TITLE
Religion should play a role in government. 번역 건에 대하여.

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#13]
- Religion should play a role in government.
- 종교는 정부에서 하는 역할이 있어야 한다.

1. play a role in 의 번역을 직역으로 해서, 국가 기관의 일부분, 혹은 국가 내에서 종교 단체의 역할을 물어보는 것으로 오인할 소지가 있습니다.
2. 정교분리에 대한 질문입니다. 국가와 종교가 분리된 근대적인 국가를 선호하느냐 마느냐에 대한 질문입니다.

번역 제안은 좀 하지를 못할 것 같고 이 부분에 대해서 좀 더 논의가 필요한 것 같습니다.

**Comment by blue-pencil** [comment]
질문의 의도를 감안하여 "종교는 정부의 활동에 영향을 끼쳐야 한다." 로 수정하였습니다. 더 나은 번역이 있다면 제안 부탁드립니다.
