### ISSUE TITLE
Children should be educated in religious or traditional values. 번역 건에 대하여.

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#14]
- Children should be educated in religious or traditional values.
- 아이들은​ ​종교적​ ​혹은​ ​전통적​ ​가치로 가르쳐야 한다.

1. be educated in은 교육을 받다입니다. be educated in physics 라고 하면 물리학을 배웠다. 정도로 해석해야하는데, 여기서는 종교적 혹은 전통적 가치만을 가르쳐야한다는 형태로 잘못 번역이 되어있습니다.

다음과 같은 번역이 나을 것 같습니다.
- 아이들은 종교적이거나 전통적인 가치를 교육 받아야한다.

**Comment by blue-pencil** [comment]
반영하였습니다. 감사합니다.
