### ISSUE TITLE
No cultures are superior to others. 번역 건에 대하여

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#15]
- No cultures are superior to others.
- 다른 문화들보다 우월한 문화는 없다.

1. 보통 No ~ are superior to others. 는 어떠한 XX도 다른 것들에 비해 우월하지 않다. 정도로 해석합니다.
2. 문화 상대주의/절대주의에 대한 질문입니다.

번역 제안입니다.
- 어떠한 문화도 다른 문화보다 우월하지 않다.

**Comment by blue-pencil** [comment]
반영하였습니다. 감사합니다.
