### ISSUE TITLE
Genetic modification is a force for good, even on humans. 번역 건에 대하여.

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#16]
- Genetic modification is a force for good, even on humans.
- 유전자 변형은 인류에도 좋은 영향을 끼친다.

1. even on humans 의 수식을 잘못 판단한 거 같습니다. 문맥상 Genetic modification on humans라고 해석을 해야합니다. even을 심지어라고 번역하면 바로 알 수 있습니다. "심지어 사람에게도"라고 번역이 되니까요.
2. a force for good의 해석이 상당히 난감합니다. 일단 이 부분은 토의를 거치는게 좋을 거 같습니다. (달라이 라마 자서전 제목이기도하고요.)

번역 제안
- 유전자 변형은 사람에게 적용 될 지라도 좋은 영향을 끼칠 것이다.

**Comment by blue-pencil** [comment]
반영하였습니다. 감사합니다.
