### ISSUE TITLE
Governments should be as concerned about foreign citizens as they are about those within their borders. 번역 건에 대하여.

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#17]
- Governments should be as concerned about foreign citizens as they are about those within their borders.
- 정부는 내국인들에 관해서와 마찬가지로 외국인들에 대해 관심을 쏟아야 한다.

1. 번역 문제입니다. winin their borders. 는 국경 내에 있는 사람으로 해석해야합니다. 내국인은 국적으로만 구별이 되는 형태인데, 국경 내의 사람들이라고 하면, 영주권자, 외국인 노동자, 불법체류자, 난민, 심지어 여행객까지 다 포함되는 광의적인 개념입니다.
2. foreign citizens는 이에 따라서, 국경 외의 타국인들로 해석을 해야합니다.
3. 결과적으로 이 질문이 묻는 것은 "국가는 국가 내의 일에만 신경 써야하는가, 국외, 특히 주변국의 일까지 신경 써야하는가"라는 정치적인 질문입니다. 이는 점수 배점이 econ과 dipl에 배정되어있지, govt에 배정되어있지 않음을 체크하셔도 알 수 있습니다.

번역을 다음과 같이 제안합니다.
- 정부는 국경 내부의 사람들을 고려하는 만큼, 외부의 사람들에게도 신경을 써야한다.

**Comment by blue-pencil** [comment]
[이 이슈](https://github.com/8values/8values.github.io/commit/b640c0390441e7d833d78b3e64908db6f0d536dc)에서 원판의 표현이 변경되어 '내국인, 외국인' 단어를 유지하겠습니다. 나은 표현이 있다면 제안 부탁드립니다.
