### ISSUE TITLE
결과페이지 인자 검증관련.

### ISSUE THREAD

**Issue by minias** [8values-ko/8values-ko.github.io#19]
results.html 파일에 GET으로 4개의 인자 e,d,g,s 의 인자 값 검증을 하시는게 아무래도 좋을듯 싶습니다.

           /*78라인 */
           for (var i=0;i<vars.length;i++) {
                   var pair = vars[i].split("=")
                   //4자리일경우만, 숫자 와 닷(.) 만 리턴
                   if(pair[0] == variable && pair[1].length < 5 ) {return pair[1].replace(/[^0-9.]/g,'')}
           }

https://8values-ko.github.io/results.html?e=99999999999954.3&d=-0.00000001&g=%27%21--&s=-10000000

**Comment by BasixKOR** [comment]
@8values 공식에 반영되면 뒤따라 반영토록 하겠습니다.

**Comment by ANEP-ET** [comment]
@minias 추가적으로, 원본 8values 레포시토리에 Issue로 (영문) 넣어주시면 감사드리겠습니다.
