### ISSUE TITLE
문제 번역에 관련된 논의가 필요합니다.

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#4]
일단, "n번 문제에 어떤 번역 오류가 있습니다." 정도로 이야기를 해야할 거 같습니다만, 번호가 붙여져 있지 않음으로 문제를 직접 언급해야할 거 같습니다. 이럴 경우,

1. 이슈를 각각 나눠서 넣어야할지 (장기적으로 각 번역 문제에 대해서 따로따로 대처가 가능함)
2. 이 타래에서 계속 이어나가야할지에 대해서 일단 정의를 해야할 거 같습니다. 

사실 이슈 관리면에서는 1번이 좋은 옵션인데, 제가 이슈를 좀 많이 쓰게 될 거 같아, 먼저 이렇게 발제를 합니다. 감사합니다.

**Comment by BasixKOR** [comment]
이슈 관리 면에서 1번을 권장드리고 싶습니다.
