### ISSUE TITLE
It is better to maintain a balanced budget than to ensure welfare for all citizens. 번역 건에 대하여

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#5]
- It is better to maintain a balanced budget than to ensure welfare for all citizens.
- 모든 시민들의 복지를 보장하는 것보다 균형예산을 유지하는 것이 낫다.

균형 예산의 경우, 일단 경제학/회계 쪽 용어이기 때문에 따로 각주를 넣는것이 어떨까요? 일단, 자세한 설명이 필요한 부분이 있어야할 거 같습니다.

참고 : [네이버 지식 백과 - 경제학 사전 - 균형예산](http://terms.naver.com/entry.nhn?docId=778743&cid=42085&categoryId=42085)

**Comment by blue-pencil** [comment]
원판에서도 별도의 각주나 설명이 없기에 이를 따르겠습니다. 당사자가 용어에 익숙하지 않을 경우 직접 찾아보는 쪽을 의도한 듯 합니다.
