### ISSUE TITLE
Military action by our nation is often necessary to protect it. 번역건에 대하여

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#6]
- Military action by our nation is often necessary to protect it.
- 자국의 군사 행동은 자국을 보호하기 위해 꼭 필요하다.

1. our nation은 우리나라로 바꾸는게 적절한 것 같습니다.
2. 번역문에서 often에 대한 번역이 빠져있습니다.
3. 번역문과 원문의 늬앙스차이가 존재합니다. 원문의 경우 "할 필요가 존재할 때가 있다"라면, 번역문에서는 "해야만한다"라는 형태로 읽혀질 소지가 있습니다.

다음과 같은 번역을 제안합니다.
- 우리나라를 지키기 위한 군사 작전은 때때로 필연적이다./필수불가결하다./필요하다.

**Comment by blue-pencil** [comment]
'필수불가결하다' 로 반영하였습니다. 감사합니다.
