### ISSUE TITLE
Wars do not need to be justified to other countries. 번역 건에 대하여

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#7]
- Wars do not need to be justified to other countries.
- 전쟁은 다른 나라들에 정당화될 필요가 없다.

직역체로 가독성이 떨어지는 부분이 있습니다.
다음과 같이 수정을 제안합니다.
- 다른 국가들에게 (자국의) 전쟁을 정당화 할 필요는 없다.

**Comment by blue-pencil** [comment]
반영하였습니다. 감사합니다.
