### ISSUE TITLE
It is more important to retain peaceful relations than to further our strength. 번역 건에 대하여

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#8]
- It is more important to retain peaceful relations than to further our strength.
- 평화로운 정세를 유지하는 것은 자국의 힘을 과시하는 것보다 중요하다.

1. 은유적 표현을 직역으로 번역한 것이 약간 문제가 된 것으로 보입니다.
2. futher our strength의 번역은 상당히 까다로워보입니다. 힘을 과시라는 표현은 적절하지 않습니다.
참고 링크 : [Nomura warns against betting too hard on further euro strength](https://www.ft.com/content/a7a3fd62-4cd2-3e9f-8267-f41d2cebebec)
늬앙스적으로 봤을 때, (retain peaceful relations에 대응) 군사력 증강이나 국력 증대 정도의 번역이 옳으리라 생각됩니다.
3. peaceful relations를 평화로운 정세로 번역하는 것도 약간 문제가 있습니다. 정세는 국내 정치와 국외 정치 둘 다 포함하는 단어입니다만, peaceful relations는 주변국간의 관계에 일축되어있는 단어라고 생각됩니다.

다음과 같은 번역을 제안합니다.
- 군사력 증강보다 (주변국과의) 평화로운 관계 유지가 더 중요하다.
- 국력 증대보다 (주변국과의) 평화로운 관계 유지가 더 중요하다.

**Comment by blue-pencil** [comment]
아래쪽 번역으로 반영하였습니다. 감사합니다.
