### ISSUE TITLE
Military spending is a waste of money. 번역 건에 대하여

### ISSUE THREAD

**Issue by benjioh5** [8values-ko/8values-ko.github.io#9]
- Military spending is a waste of money.
- 군사력에​ ​돈을​ ​쓰는​ ​것은​ ​돈​ ​낭비이다.

1. [네이버 사전 - military spending](http://endic.naver.com/enkrEntry.nhn?sLn=kr&entryId=429078fdfb78419d9355a2b59c384a8d) 에서 볼 수 있듯이, Military spending을 군비로 번역하는게 옳은 것 같습니다. 군사력과 군비는 완벽히 비례 관계에 볼 수 없습니다.

번역 제안은 다음과 같습니다.
- 군사 비용(군비)은 돈 낭비이다.

**Comment by blue-pencil** [comment]
반영하였습니다. 감사합니다.
